DATA:
  IMAGE_ROOT: "/data/ephemeral/home/data/train/DCM"
  LABEL_ROOT: "/data/ephemeral/home/data/train/outputs_json"
  TEST_IMAGE_ROOT: "/data/ephemeral/home/data/test/DCM"
  CLASSES: [
      'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
      'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
      'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
      'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
      'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
      'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
  ]

TRAIN: &train_settings
  BATCH_SIZE: 8
  VAL_EVERY: 5
  EPOCHS: 30
  LR: 0.0001
  RANDOM_SEED: 21

MODEL:
  SAVED_DIR: "./saved_model"
  MODEL_NAME: "fcn_resnet50_best_model.pt"

INFERENCE:
  OUTPUT_DIR: "./inference"
  CSV_NAME: "output.csv"

WANDB:
  PROJECT_NAME: "semantic-segmentation"
  ENTITY: "lv2-ss-"
  RUN_NAME: "baseline" # 실험 이름 바꿔줘요.
  NOTES: "train with wandb" # 특이사항 혹은 tag로 설명이 안되면 추가해주시면 됩니다. 
  TAGS: ["fcn", "resnet50"]
  CONFIGS: *train_settings
